package com.mazenet.mani.gurugubera.Model

class OfflineReceiptsdetailsmodel {
    var of_recno: String =""
    var of_offrecno: String =""
    var of_enrolid: String =""
    var of_otherbranch: String =""
    var of_customerid: String =""
    var of_receiptdate: String =""
    var of_groupid: String =""
    var of_ticketno: String =""
    var of_adjustid: String =""
    var of_receivedamount: String =""
    var of_paytypeid: String =""
    var of_debitto: String =""
    var of_chequeno: String =""
    var of_chequedate: String =""
    var of_chequecleardate: String =""
    var of_banknameid: String =""
    var of_chequebranchname: String =""
    var of_transno: String =""
    var of_transdate: String =""
    var of_receipttime: String =""
    var of_printed: String =""
    var of_remarks: String =""
    var of_posted: String =""
    var custname: String =""
    var custcode: String =""
    var custmobile: String =""
    var custphone: String =""
    var penalty: String =""
    var bonus: String =""
    var installmentnos: String =""
    var of_advance: String =""
    var of_advanceonly: String =""
}